package de.tudarmstadt.gdi1.project.analysis.monoalphabetic;

import de.tudarmstadt.gdi1.project.alphabet.Alphabet;
import de.tudarmstadt.gdi1.project.alphabet.Dictionary;
import de.tudarmstadt.gdi1.project.alphabet.Distribution;
import de.tudarmstadt.gdi1.project.analysis.EncryptionOracle;
import de.tudarmstadt.gdi1.project.cipher.substitution.monoalphabetic.MonoalphabeticCipher;

/**
 * Created by Hannes on 2/24/14.
 *
 * @author Hannes Güdelhöfer
 */
public class MonoalphabeticCpaNpaCryptanalysisImpl implements MonoalphabeticCpaNpaCryptanalysis {
	@Override
	public char[] knownPlaintextAttack(String ciphertext, String plaintext, Alphabet alphabet) {
		char[] key = new char[alphabet.size()];

		//all not known characters are supposed to be ' ',so in the beginning every character will be
		for(int i = 0; i < alphabet.size(); i++) {
			key[i] = ' ';
		}
		//generate key out of plain and ciphertext, using the index of plaintext.charAt[n]
		for(int n = 0; n < ciphertext.length(); n++) {
			key[alphabet.getIndex(plaintext.charAt(n))] = ciphertext.charAt(n);
		}

		return key;
	}

	/**
	 * Attack to determine the used key based on a given cipher- and
	 * (corresponding) plaintext and a given distribution on the alphabet.
	 *
	 * @param ciphertext   the ciphertext
	 * @param plaintext    the corresponding plaintext
	 * @param distribution the distribution
	 * @return the key, a part of the key, or null
	 */
	@Override
	public Object knownPlaintextAttack(String ciphertext, String plaintext, Distribution distribution) {
		return knownPlaintextAttack(ciphertext, plaintext, distribution.getAlphabet());
	}

	/**
	 * Attack to determine the used key based on a given cipher- and
	 * (corresponding) plaintexts and a given distribution on the alphabet.
	 *
	 * @param ciphertext
	 * @param plaintext
	 * @param distribution The distribution
	 * @param dictionary   @return the key, a part of the key, or null
	 */
	@Override
	public Object knownPlaintextAttack(String ciphertext, String plaintext, Distribution distribution, Dictionary dictionary) {
		return knownPlaintextAttack(ciphertext, plaintext, distribution);
	}

	/**
	 * Attack to determine the used key based given an oracle that allows to
	 * encrypt arbitrary plaintexts.
	 *
	 * @param oracle   An object that allows to generate arbitrary encryptions
	 * @param alphabet The plaintext alphabet
	 * @return the key or null if the key could not be recoverd
	 */
	@Override
	public char[] chosenPlaintextAttack(EncryptionOracle<MonoalphabeticCipher> oracle, Alphabet alphabet) {
		String encryptedAlphabet;
		String plaintext = "";
		char[] usedAlphabet = alphabet.asCharArray();

		//convert alphabet to String for use in oracle and knownPlaintextAttack
		for(char c : usedAlphabet) {
			plaintext += c;
		}
		//encrypt alphabet
		encryptedAlphabet = oracle.encrypt(plaintext);
		//return key generated by KnownPlaintextAttack
		return knownPlaintextAttack(encryptedAlphabet, plaintext, alphabet);
	}
}
